name: C++ CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Compile
      run: g++ -std=c++17 App/T_ConsoleLab.cpp tests/tests.cpp -o test

    - name: Run tests
      run: ./test
